### ISSUE TITLE
Date Changes- Curator Dashboard Page

### ISSUE THREAD

**Issue by shruthi-raghuraman** [CCI-MOC/curator#4]
### Description
- When ui is started make sure the default page is dashboard with appropriate dates is filled in. 
- Identify edge cases with the time constraints.

### Date Specification Example
- Default start/end is within current day
- Default time (involves 15 mins buffer)

> *At 12:20 on 03/09/202, Start Date&time 03/09/2021 11:00 AM, End Date&time 03/09/2021 12:00 PM*
> *At 12:10 on 03/09/2021, Start Date&time 03/09/2021 10:00 AM, End Date&time 03/09/2021 11:00 AM*

There fore 12:15 PM is considered a **cutoff** time

**Comment by gagansk** [comment]
@shruthi-raghuraman Please consider Timezone. (The query time should always be ET)
